#!/bin/bash
###
# File: diy-nas-start
# Project: files
# File Created: Monday, 25th January 2021 2:18:41 am
# Author: Josh.5 (jsunnex@gmail.com)
# -----
# Last Modified: Monday, 25th January 2021 2:30:43 am
# Modified By: Josh.5 (jsunnex@gmail.com)
###


# Ensure we are run as root...
if [[ $(id -u) -gt 0 ]]; then
    echo "ERROR! This needs to be run as root... Exiting..."
    exit 1
fi


PROJECT_PATH="/opt/diy-nas"


[[ ! -e ${PROJECT_PATH}/source/install.env ]] && echo "Unable to run as we are missing project files in '${PROJECT_PATH}/source'... Exit!" && exit 1
source ${PROJECT_PATH}/source/install.env


if [[ ! -f ${PROJECT_PATH}/docker-compose.yml || ! -f ${PROJECT_PATH}/config/config.env ]]; then
    echo "Missing either the docker-compose file or it's environmont config file... Exit!"
    exit 1
else

    echo
    echo -e "${CLMAG}Stopping D.I.Y. NAS System ${CNORM}"
    echo

    # Bring down containers
    _stage_header "Bringing down system Docker containers"
    docker-compose -f ${PROJECT_PATH}/docker-compose.yml --env-file ${PROJECT_PATH}/config/config.env down &>> ${SCRIPT_LOG_FILE}
    _update_stage_header ${?}

    echo
fi
