###
# File: docker-compose.yml
# Project: diy-nas
# File Created: Wednesday, 20th January 2021 7:24:01 am
# Author: Josh.5 (jsunnex@gmail.com)
# -----
# Last Modified: Wednesday, 20th January 2021 11:03:10 pm
# Modified By: Josh.5 (jsunnex@gmail.com)
###


---

version: '2'
services:

  nginx:
    image: linuxserver/nginx:latest
    container_name: main-proxy
    labels:
      - "service=system"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /opt/diy-nas/system_appdata/main-proxy:/config
    ports:
      - 80:80
    restart: always

  muximux:
    image: ghcr.io/linuxserver/muximux:a2b403f5-ls70 # Lock in this version (shouldn't need to ever update it...)
    container_name: landing-page
    labels:
      - "service=system"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /opt/diy-nas/system_appdata/landing-page:/config
    ports:
      - 5002:80
    restart: always

  docker-compose-ui:
    image: rururukenken/docker-compose-ui:latest
    container_name: docker-compose-ui
    labels:
      - "service=system"
    working_dir: /opt/diy-nas/config/docker-compose-files
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/diy-nas/config/docker-compose-files:/opt/diy-nas/config/docker-compose-files
    ports:
      - 5000:5000
    restart: always

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    labels:
      - "service=system"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /opt/diy-nas/config/appdata/heimdall:/config
    ports:
      - 5001:80
      - 443:443
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -l service=system -H unix:///var/run/docker.sock
    labels:
      - "service=system"
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/diy-nas/config/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    labels:
      - "service=system"
    ports:
      - 8000:8000
    volumes:
      - /opt/diy-nas/config/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/diy-nas/config/docker-compose-files:/docker-compose-files
    environment:
      - COMPOSE_DIR=/docker-compose-files/
    restart: always
